version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 504secret
    volumes: [ dbdata:/var/lib/postgresql/data ]
  api:
    build: ../packages/api
    depends_on: [ db ]
    environment:
      DATABASE_URL: postgres://postgres:504secret@db:5432/postgres
    ports: [ "3001:3001" ]
volumes:
  dbdata:
